[RB-31] Sign Up
Code-the-Dream-School/hh-team6-front pull request #10
Opened 2024-11-20 08:01 UTC by EvgeniiRychkov

## Description
Create Sign Up page

## Changes
Create Sign Up page, create Input component

## Related issues
RB-31

## Screenshots
<img width="549" alt="Screenshot 2024-11-20 at 12 01 39 AM" src="https://github.com/user-attachments/assets/5fcc72c4-223c-45a5-975f-5879b9abab9c">

2024-11-20 09:29 UTC, in43sh requested changes

2024-11-20 09:29 UTC, in43sh commented on src/api/DBRequests.jsx
> +      error?.response?.data?.error || 'An unexpected error occurred';
You could extract `An unexpected error occurred` to a const variable. Small change but might be worth doing it considering that we will have more requests in the future

2024-11-20 09:29 UTC, in43sh commented on src/api/DBRequests.jsx
> +export const register = async ({ email, password, firstName, lastName }) => {
You could combine these two functions into one:
```js
import axios from 'axios';

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL;

const handleApiRequest = async (url, payload) => {
  try {
    const { data, status } = await axios.post(`${API_BASE_URL}${url}`, payload);
    return { data, status };
  } catch (error) {
    const errorMessage =
      error?.response?.data?.message || 'An unexpected error occurred';
    throw new Error(errorMessage);
  }
};

export const login = (credentials) =>
  handleApiRequest('/api/v1/login', credentials);

export const register = (userData) =>
  handleApiRequest('/api/v1/register', userData);

```

2024-11-20 09:29 UTC, in43sh commented on src/components/Form/Input.jsx
> +const Input = ({ id, name, type, value, onChange, children, error }) => {
You can remove `return` here:
```js
const Input = ({ id, name, type, value, onChange, children, error }) => (
  <div className="mb-3 flex w-full flex-col gap-1">
    <label htmlFor={id}>{children}</label>
    <input
      id={id}
      name={name}
      type={type}
      value={value}
      onChange={onChange}
      className={'w-full rounded border-2 border-gray p-2'}
    />
    {error && <p className="text-red">{error}</p>}
  </div>
);
```

2024-11-20 09:29 UTC, in43sh commented on src/hooks/UseSignUpForm.jsx
> +  const handleChange = ({ target: { name, value } }) => {
Very minor but if you want, you could remove curly braces:
```js
const handleChange = ({ target: { name, value } }) =>
    setForm((prevForm) => ({ ...prevForm, [name]: value }));
```

2024-11-20 09:29 UTC, in43sh commented on src/hooks/UseSignUpForm.jsx
> +    if (Object.keys(validationErrors).length > 0) {
You could replace it with smaller code piece:
```js
if (Object.keys(validationErrors).length) return;
```

2024-11-20 09:29 UTC, in43sh commented on src/hooks/UseSignUpForm.jsx
> +      const result = await register(form);
You can use destructuring here as you've done before by doing:
```js
const { data, status } = await register(form);
```

2024-11-20 09:29 UTC, in43sh commented on src/hooks/UseSignUpForm.jsx
> +const UseSignUpForm = () => {
As this is a React custom hook, I think you should rename both the function and the filename to `useSignUpForm`

2024-11-20 09:29 UTC, in43sh commented on src/pages/auth/SignIn.jsx
> +            onChange={handleChange}
I think `value` should go before `onChange`. Here and in all other cases

2024-11-20 09:29 UTC, in43sh commented on src/pages/auth/SignIn.jsx
>                className="flex w-full flex-col underline"
Do you really need all these classes for the Link? Shouldn't it be better to only have `underline`?

2024-11-20 09:30 UTC, in43sh commented
Looks awesome!

2024-11-20 16:08 UTC, brandon91warren approved these changes

2024-11-21 02:07 UTC, in43sh approved these changes

2024-11-21 02:08 UTC, merged