[RB-16] About us page
Code-the-Dream-School/hh-team6-front pull request #12
Opened 2024-11-21 04:44 UTC by liuba83

## Description
Create About us page

## Changes
Create About.jsx component

## Related issues

## Screenshots
<img width="780" alt="Screen Shot 2024-11-20 at 10 41 52 PM" src="https://github.com/user-attachments/assets/53594c17-ea86-415a-b240-986317149e5d">

2024-11-22 07:35 UTC, in43sh requested changes
Good work overall! Some minor changes needed but still you did a good job!

2024-11-22 07:35 UTC, in43sh commented on src/assets/images/square.png
I understand that this file was here for development purposes but we can't merge such file into the `dev` branch. You would have to replace it with a default photo or something else.

2024-11-22 07:35 UTC, in43sh commented on src/components/TeamMemberCard.jsx
> +// import avatar from '../assets/images/default-avatar.jpeg';
You should always remove comments like this before creating a new PR.

2024-11-22 07:35 UTC, in43sh commented on src/components/TeamMemberCard.jsx
You should run command `npm run format` as some css classes are not in order.

2024-11-22 07:35 UTC, in43sh commented on src/pages/About.jsx
Same here, some css classes are not in order. `npm run format` will fix it.

2024-11-22 07:35 UTC, in43sh commented on src/pages/About.jsx
>  import React from 'react';
You can also delete this line

2024-11-22 07:35 UTC, in43sh commented on src/components/TeamMemberCard.jsx
> +import React from 'react';
You can delete this line as beginning from recent versions you don't need to import React in your component.

2024-11-22 07:35 UTC, in43sh commented on src/components/TeamMemberCard.jsx
> +    <div className="max-w-sm rounded overflow-hidden shadow-lg mb-10 bg-lightBlue py-5 px-6">
I think you can remove these two tailwind classes: `max-w-sm overflow-hidden`.

2024-11-22 07:35 UTC, in43sh commented on src/pages/About.jsx
> +  const mentorCards = mentors.map((item, index) => (
I think this should be called `mentorsCards`

2024-11-22 07:35 UTC, in43sh commented on src/pages/About.jsx
> +        {mentorCards}
Replace it with `mentorsCards`.

2024-11-22 07:35 UTC, in43sh commented on src/pages/About.jsx
> +      name: 'Evgenii',
You should add people's last names here.

2024-11-22 07:35 UTC, in43sh commented on src/pages/About.jsx
> +    <div className="w-full flex flex-col items-center bg-white">
You don't need `bg-white` as the page is already white by default.

2024-11-22 07:35 UTC, in43sh commented on src/pages/About.jsx
> +      <p className="px-10 pb-10 flex flex-col items-center w-full font-body text-justify">
Minor Tailwind suggestions:
- Horizontal padding should be 60 pixels on the desktop version
- `flex w-full flex-col items-center` can be removed
- Font size should be 24px and line height should be 52px

2024-11-22 07:35 UTC, in43sh commented on src/pages/About.jsx
> +  const frontend = [
There could be a better way to do it, but this will work for now

2024-11-25 03:12 UTC, in43sh commented on src/pages/About.jsx
>  import React from 'react';
Evegenii and I talked offline and we don't need to remove it anymore.

2024-11-26 05:06 UTC, in43sh approved these changes

2024-11-26 17:11 UTC, VadimDmitr approved these changes
Great job, Liuba! If yesterday I had questions about the font, lineHeight, and text at the bottom of the page, today I can see that everything is well-adjusted and looks excellent across all devices.

2024-11-26 18:39 UTC, in43sh approved these changes

2024-11-26 19:30 UTC, VadimDmitr approved these changes
Awesome!

2024-11-26 22:29 UTC, merged