[RB-17] Account
Code-the-Dream-School/hh-team6-front pull request #21
Opened 2024-12-01 04:23 UTC by EvgeniiRychkov

## Description
[RB-17] Account
## Changes
Create a Left Menu and an Account Button in the Header. Add a context menu for the Account Button in the mobile version.
## Related issues
[RB-17] Account
## Screenshots
<img width="740" alt="Screenshot 2024-11-30 at 8 07 57 PM" src="https://github.com/user-attachments/assets/55f4fe9e-bfd1-451a-b413-c827b28b639b">
<img width="588" alt="Screenshot 2024-11-30 at 8 08 10 PM" src="https://github.com/user-attachments/assets/e9649700-f716-4e04-997a-c7636e0e2be3">

2024-12-02 11:53 UTC, in43sh requested changes
Overall, really nice work done. I like that your code is clean and simple, it's easy to read it. Other than a few minor changes, it was hard to find anything.

2024-12-02 11:53 UTC, in43sh commented on src/components/header/NavBar.jsx
> +          <button onClick={clearUserSession} className="hidden sm:flex">
Can you use Button from Headless UI?

2024-12-02 11:53 UTC, in43sh commented on src/components/header/AccountButton.jsx
> +              <>
You can remove this empty fragment element.

2024-12-02 11:53 UTC, in43sh commented on src/components/account/LeftMenu.jsx
Maybe you could use more semantic tags like `<aside>`, `<nav>`, `<ul>`, `<li>`? Other than that, nothing to add.

2024-12-02 11:53 UTC, in43sh commented on src/components/header/AccountButton.jsx
Can you add some comments so it's easier to understand where is desktop and where is mobile version?

2024-12-02 11:53 UTC, in43sh commented on src/components/header/AccountButton.jsx
Maybe something like:
```js
{/* Desktop */}
```
and the same for mobile. Otherwise, right now it's a little hard to understand it.

2024-12-02 11:53 UTC, in43sh commented on src/components/account/LeftMenu.jsx
> +      <ChangePageButton page="myBooks" label="My Book Listings" />
It would be nice if links sidebar nav links had some kind of on:hover animation.

2024-12-02 11:53 UTC, in43sh commented on src/components/account/LeftMenu.jsx
> +      <Button
This button could also have a on:hover animation.

2024-12-02 13:59 UTC, in43sh commented on src/components/account/LeftMenu.jsx
> +        + Add New Listing
Do you think it's possible to extract a styled button to a separated component?

2024-12-03 00:35 UTC, VadimDmitr reviewed
Awesome job, Evgenii! The design looks great and well-structured. Just a couple of suggestions noted in the comments.

2024-12-03 00:35 UTC, VadimDmitr commented on src/components/header/AccountButton.jsx
> +              {menuLink('savedBooks', 'Saved books', close)}
A capital "Saved Books" could better match the style of the design and the "Left Menu".

2024-12-03 00:35 UTC, VadimDmitr commented on src/components/account/LeftMenu.jsx
> +    <div className="ml-5 hidden rounded-md border border-gray p-3 sm:block">
To match the Figma design, I’d add more space between the items using `space-y-4`, for example:
`<div className="ml-5 hidden rounded-md border border-gray p-3 sm:block space-y-4">`.

2024-12-04 00:19 UTC, in43sh approved these changes

2024-12-04 00:25 UTC, merged