[RB-15] Home page
Code-the-Dream-School/hh-team6-front pull request #22
Opened 2024-12-03 05:51 UTC by liuba83

## Description
Create Home page that contains image, search form, text bullet points with icons, books list

## Changes
Add new page

## Related issues
RB-15

## Screenshots
<img width="285" alt="Screen Shot 2024-12-02 at 11 49 15 PM" src="https://github.com/user-attachments/assets/59395069-902d-4e34-91c0-518483d0677f">

2024-12-03 19:00 UTC, EvgeniiRychkov reviewed
Looks great, but I think more responsive design needs to be added so that the main page looks like the mockups in Figma. Also, note that six books don't fit on the screen and don't wrap to a new row.

2024-12-03 19:06 UTC, EvgeniiRychkov commented on src/pages/Home.jsx
> +            className="mt-7 w-full rounded-md bg-darkGreen p-2 font-semibold tracking-wide text-white"
You can add it

`transition-transform duration-150 hover:bg-darkGreenHover active:scale-95`

2024-12-04 18:48 UTC, VadimDmitr reviewed
Great work, Liuba! It looks really good. I agree with Evgenii’s comment. Since the presentation will start with the home page, the design should be optimized for desktop and most likely starting from tablet resolution.

2024-12-07 07:12 UTC, in43sh approved these changes

2024-12-07 14:38 UTC, VadimDmitr requested changes
Looks good! But the book section seems slightly shifted to the left. For tablet and larger devices, we can align the book section like:
 ```
<h1 className="mb-8 tablet:ml-20 font-headings text-xl font-semibold md:self-start">
    Recently added books
  </h1>
  <div className="tablet:ml-20">
    <BooksList list={booksList} />
  </div>
</div>
```
Feel free to adjust margins or other styles as you see fit!

2024-12-08 23:22 UTC, VadimDmitr approved these changes
The page and responsiveness look awesome! Thank you for changes!

2024-12-08 23:45 UTC, EvgeniiRychkov approved these changes

2024-12-08 23:47 UTC, merged

2024-12-09 02:09 UTC, in43sh approved these changes