[RB-22] Profile Edit Page (Account Folder)
Code-the-Dream-School/hh-team6-front pull request #31
Opened 2024-12-19 19:17 UTC by brandon91warren

## Description
Update Profile Page
## Changes
Update Profile Page

## Related issues
Email disappearing. Now fixed 
## Screenshots
<img width="1184" alt="Screenshot 2024-12-18 at 10 08 23 PM" src="https://github.com/user-attachments/assets/49b4c02b-45c6-4790-868e-6c32550e536a" />
<img width="1197" alt="Screenshot 2024-12-18 at 10 07 58 PM" src="https://github.com/user-attachments/assets/64aa736d-064e-4c52-b117-44a223f9f6a4" />
<img width="1148" alt="Screenshot 2024-12-18 at 10 08 06 PM" src="https://github.com/user-attachments/assets/176b595a-6928-4550-80d4-cef193b8fae8" />

2024-12-21 12:01 UTC, in43sh requested changes
Overall, nice job. I would only suggest a couple small changes.

2024-12-21 12:01 UTC, in43sh commented on src/pages/account/UpdateProfile.jsx
> +          style={{
I think you should be able to pass Tailwind classes using props. Maybe instead of `style` you can call the props `className`.

2024-12-21 12:01 UTC, in43sh commented on src/pages/account/UpdateProfile.jsx
> +        const response = await updateProfile(headers, formData, token);
I think you could delete email from `formData` as it won't change.

2024-12-23 11:56 UTC, in43sh approved these changes

2024-12-23 13:21 UTC, VadimDmitr approved these changes
Everything works as expected, good job, Brandon!

2024-12-23 17:00 UTC, merged