Feature/rb 26 cart
Code-the-Dream-School/hh-team6-front pull request #35
Opened 2024-12-31 00:08 UTC by Tanyaa-a

## Description
add cartPage and cart functionality, delete book from cart, add book to cart from book page

## Changes
-- DBRequests.jsx 
-- Cart.jsx
-- Book.jsx
## Related issues
<img width="956" alt="Screenshot 2024-12-30 at 4 05 40 PM" src="https://github.com/user-attachments/assets/b921e5d9-c7d7-45af-a720-2c00340a7e6f" />

## Screenshots
![Screenshot 2024-12-30 at 3 41 17 PM](https://github.com/user-attachments/assets/80106acf-9c5b-40ad-b0a4-6b0ff2fc09de)
![Screenshot 2024-12-30 at 3 41 09 PM](https://github.com/user-attachments/assets/fb061634-8245-4930-9b43-ca7df35fdacd)
![Screenshot 2024-12-30 at 3 41 03 PM](h
![Screenshot 2024-12-29 at 11 54 46 
![Screenshot 2024-12-29 at 11 54 24 PM](https://github.com/user-attachments/assets/75f14ba8-7474-4664-b4fd-3aa725b863af)
PM](https://github.com/user-attachments/assets/f14c7767-d8a3-4834-b00f-a5bf6c17df5f)
ttps://github.com/user-attachments/assets/e2c59e68-0c34-48db-a344-e256ae7bcc46)

2025-01-02 02:32 UTC, in43sh requested changes
Really nice job in this PR! Other than some small things, I noticed that adding to the cart doesn't always work for me properly: I can't add some books, and after adding some books I'm not being redirected to the `/cart` page. Also, I'm getting some console errors when trying to delete items from the cart.

2025-01-02 02:32 UTC, in43sh commented on .env.example
Why did you delete this file?

2025-01-02 02:32 UTC, in43sh commented on src/api/DBRequests.jsx
> +        Authorization: `Bearer ${token}`,
Instead of passing a token as a string, I would centralize getting token by doing it inside a separate function

2025-01-02 02:32 UTC, in43sh commented on src/api/DBRequests.jsx
> +      error?.response?.data?.msg ||
Very minor, but as this is repeated across many request, it's time to consider extracting error message to a separate function.

2025-01-02 02:32 UTC, in43sh commented on src/pages/books/Book.jsx
> +      navigate('/cart'); // Redirect to the cart page after adding to cart
I'm on the Book page and it's not redirecting me to the Cart page after adding a book.

2025-01-02 02:32 UTC, in43sh commented on src/pages/books/Book.jsx
> +              {isAddingToCart ? 'Adding...' : 'Add to cart'}
`Adding...` message disappears too fast so for user it's hard to understand that an item was added to the cart. You might want to consider adding something to the UI for user to understand that it happened. You could change the button title to `Added` and add a number next to the cart icon reflecting the amount of items in the cart.

2025-01-02 02:32 UTC, in43sh commented on src/pages/books/Book.jsx
> +      navigate('/cart'); // Redirect to the cart page after adding to cart
The comments explaining the navigate calls might be redundant since the code is self-explanatory. Removing these comments could make the code cleaner and more concise.

2025-01-02 02:32 UTC, in43sh commented on src/pages/cart/Cart.jsx
I would extract some code here into separate components to make the code easier to read. You could consider extracting at least `CartItem`, but also `CartSummary`, `SellerGroup`, and `SavedForLater`.

2025-01-02 02:32 UTC, in43sh commented on src/pages/cart/Cart.jsx
> +  const itemsBySeller = cartItems.reduce((acc, item) => {
I would use `useMemo` here.

2025-01-02 04:37 UTC, EvgeniiRychkov commented on src/api/DBRequests.jsx
> +      error?.response?.data?.msg ||
I think it is better to do a separate task.

2025-01-02 04:38 UTC, EvgeniiRychkov commented on src/pages/books/Book.jsx
> +              {isAddingToCart ? 'Adding...' : 'Add to cart'}
I think we already have the Notification task about it

2025-01-02 05:53 UTC, Tanyaa-a commented on .env.example
added

2025-01-02 05:58 UTC, Tanyaa-a commented on src/api/DBRequests.jsx
> +        Authorization: `Bearer ${token}`,
Great idea but as it was done  this way in previous functions  of the file so I just followed the pattern

2025-01-02 05:59 UTC, Tanyaa-a commented on src/api/DBRequests.jsx
> +      error?.response?.data?.msg ||
Thank you will think about that

2025-01-02 06:01 UTC, Tanyaa-a commented on src/pages/books/Book.jsx
> +      navigate('/cart'); // Redirect to the cart page after adding to cart
If the book is unique it is added. Need to work on errors if the book is already in the cart

2025-01-03 06:43 UTC, Tanyaa-a commented on src/pages/books/Book.jsx
> +              {isAddingToCart ? 'Adding...' : 'Add to cart'}
removed

2025-01-03 10:30 UTC, in43sh requested changes
I like how you split Cart into multiple components but after a closer look I saw some more improvements. After you fix those, I believe this PR should be good to go.

2025-01-03 10:30 UTC, in43sh commented on src/pages/cart/CartItem.jsx
> +            <button className="hover:underline">Save for later</button>
Please use Button from Headless UI here and for all other buttons

2025-01-03 10:30 UTC, in43sh commented on src/pages/cart/CartSummary.jsx
> +        <button className="mt-2 w-full rounded-md bg-red px-6 py-1 text-white hover:bg-redHover">
Please use Button from Headless UI

2025-01-03 10:30 UTC, in43sh commented on src/pages/cart/CartItem.jsx
> +CartItem.propTypes = {
Very minor but all other components have an empty line between component and prop types. It would be nice to have to keep it consistent.

2025-01-03 10:30 UTC, in43sh commented on src/pages/cart/CartSummary.jsx
> +};
Please add an empty line between the component and prop types.

2025-01-03 10:30 UTC, in43sh commented on src/pages/cart/CartSummary.jsx
> +      <div className="flex items-center justify-between pb-2">
Following DRY principle, I would extract `tax`, `shipping fee`, and `total` to a separate compont (eg `CartSummaryItem` or `CartSummaryRow`) because of its repetitive structure.

2025-01-03 10:30 UTC, in43sh commented on src/pages/cart/CartSummary.jsx
> +const CartSummary = ({ totals }) => {
You could use destructuring for `tax`, `shippingFee`, and `total` here.

2025-01-03 10:30 UTC, in43sh commented on src/pages/cart/CartItem.jsx
> +const CartItem = ({ item, handleDelete }) => {
You could destructure values inside `item` to have easier access to them.

2025-01-03 19:18 UTC, Tanyaa-a commented on src/pages/cart/CartItem.jsx
> +            <button className="hover:underline">Save for later</button>
changed

2025-01-06 07:09 UTC, in43sh approved these changes

2025-01-06 17:22 UTC, merged